/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin': RouteRecordInfo<
      '/admin',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/analytics': RouteRecordInfo<
      '/analytics',
      '/analytics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/calendar': RouteRecordInfo<
      '/calendar',
      '/calendar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/forbidden': RouteRecordInfo<
      '/forbidden',
      '/forbidden',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/invoice': RouteRecordInfo<
      '/invoice',
      '/invoice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/messages': RouteRecordInfo<
      '/messages',
      '/messages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notification': RouteRecordInfo<
      '/notification',
      '/notification',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reset-password': RouteRecordInfo<
      '/reset-password',
      '/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/schedule': RouteRecordInfo<
      '/schedule',
      '/schedule',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user': RouteRecordInfo<
      '/user',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin.vue': {
      routes:
        | '/admin'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/analytics.vue': {
      routes:
        | '/analytics'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/calendar.vue': {
      routes:
        | '/calendar'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/forbidden.vue': {
      routes:
        | '/forbidden'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/invoice.vue': {
      routes:
        | '/invoice'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/messages.vue': {
      routes:
        | '/messages'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/notification.vue': {
      routes:
        | '/notification'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/reset-password.vue': {
      routes:
        | '/reset-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/schedule.vue': {
      routes:
        | '/schedule'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/user.vue': {
      routes:
        | '/user'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
